### ISSUE TITLE
Implement Test Deployer

### ISSUE THREAD

**Issue by jaredoconnell** [arcalot/arcaflow-engine-deployer-test-impl#1]
## Please describe what you would like to see in this project

We need an implementation of the deployer for test purposes.

It should meet the requirements of the deployer API, and it should run a plugin with basic inputs and outputs for test purposes.

The test plugin built into this should just run in the same process, which will require properly directing its stdio to the engine.

## Please describe your use case

- Basic test cases in the engine, to test that it properly deploys, retrieves plugin schemas, and runs workflows.
- Special cases, like plugin ordering and stopping

**Comment by dustinblack** [comment]
test comment for jira

**Comment by mfleader** [comment]
Depends on
- [x] [fixing golang sdk ATP transaction interruption bug](https://github.com/arcalot/arcaflow-plugin-sdk-go/issues/39)
